Name: awscli
Version: 1.9.7
Release: 1.el7
Summary: This package provides a unified command line interface to Amazon Web Services.
Group: Productivity/Networking/Web/Servers
License: Apache Software License.
Url: https://pypi.python.org/pypi/awscli
Source: %{name}-%{version}.tar.gz

BuildRoot: %{_tmppath}/%{name}-%{version}-build
BuildRequires: epel-release
BuildRequires: python-pip
Requires: python
BuildArch: noarch

%description
This package provides a unified command line interface to Amazon Web Services.

%prep
curl -s -o /data/rpmbuild/SOURCES/%{package}-${version}.tar.gz https://pypi.python.org/packages/source/a/%{name}/%{name}-%{version}.tar.gz

%install
rm -Rf %{buildroot}
pip install --install-option="--prefix=%{buildroot}" awscli

%clean
rm -rf %{buildroot}

%files
/bin/aws
/bin/aws.cmd
/bin/aws_completer
/bin/aws_zsh_completer.sh
/bin/jp.py
/bin/pyrsa-decrypt
/bin/pyrsa-decrypt-bigfile
/bin/pyrsa-encrypt
/bin/pyrsa-encrypt-bigfile
/bin/pyrsa-keygen
/bin/pyrsa-priv2pub
/bin/pyrsa-sign
/bin/pyrsa-verify
/bin/rst2html.py
/bin/rst2latex.py
/bin/rst2man.py
/bin/rst2odt.py
/bin/rst2odt_prepstyles.py
/bin/rst2pseudoxml.py
/bin/rst2s5.py
/bin/rst2xetex.py
/bin/rst2xml.py
/bin/rstpep2html.py
/lib/python2.7/site-packages/awscli-1.9.7-py2.7.egg-info/PKG-INFO
/lib/python2.7/site-packages/awscli-1.9.7-py2.7.egg-info/SOURCES.txt
/lib/python2.7/site-packages/awscli-1.9.7-py2.7.egg-info/dependency_links.txt
/lib/python2.7/site-packages/awscli-1.9.7-py2.7.egg-info/installed-files.txt
/lib/python2.7/site-packages/awscli-1.9.7-py2.7.egg-info/requires.txt
/lib/python2.7/site-packages/awscli-1.9.7-py2.7.egg-info/top_level.txt
/lib/python2.7/site-packages/awscli/__init__.py
/lib/python2.7/site-packages/awscli/__init__.pyc
/lib/python2.7/site-packages/awscli/__init__.pyo
/lib/python2.7/site-packages/awscli/argparser.py
/lib/python2.7/site-packages/awscli/argparser.pyc
/lib/python2.7/site-packages/awscli/argparser.pyo
/lib/python2.7/site-packages/awscli/argprocess.py
/lib/python2.7/site-packages/awscli/argprocess.pyc
/lib/python2.7/site-packages/awscli/argprocess.pyo
/lib/python2.7/site-packages/awscli/arguments.py
/lib/python2.7/site-packages/awscli/arguments.pyc
/lib/python2.7/site-packages/awscli/arguments.pyo
/lib/python2.7/site-packages/awscli/clidocs.py
/lib/python2.7/site-packages/awscli/clidocs.pyc
/lib/python2.7/site-packages/awscli/clidocs.pyo
/lib/python2.7/site-packages/awscli/clidriver.py
/lib/python2.7/site-packages/awscli/clidriver.pyc
/lib/python2.7/site-packages/awscli/clidriver.pyo
/lib/python2.7/site-packages/awscli/compat.py
/lib/python2.7/site-packages/awscli/compat.pyc
/lib/python2.7/site-packages/awscli/compat.pyo
/lib/python2.7/site-packages/awscli/completer.py
/lib/python2.7/site-packages/awscli/completer.pyc
/lib/python2.7/site-packages/awscli/completer.pyo
/lib/python2.7/site-packages/awscli/customizations/__init__.py
/lib/python2.7/site-packages/awscli/customizations/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/addexamples.py
/lib/python2.7/site-packages/awscli/customizations/addexamples.pyc
/lib/python2.7/site-packages/awscli/customizations/addexamples.pyo
/lib/python2.7/site-packages/awscli/customizations/argrename.py
/lib/python2.7/site-packages/awscli/customizations/argrename.pyc
/lib/python2.7/site-packages/awscli/customizations/argrename.pyo
/lib/python2.7/site-packages/awscli/customizations/arguments.py
/lib/python2.7/site-packages/awscli/customizations/arguments.pyc
/lib/python2.7/site-packages/awscli/customizations/arguments.pyo
/lib/python2.7/site-packages/awscli/customizations/assumerole.py
/lib/python2.7/site-packages/awscli/customizations/assumerole.pyc
/lib/python2.7/site-packages/awscli/customizations/assumerole.pyo
/lib/python2.7/site-packages/awscli/customizations/awslambda.py
/lib/python2.7/site-packages/awscli/customizations/awslambda.pyc
/lib/python2.7/site-packages/awscli/customizations/awslambda.pyo
/lib/python2.7/site-packages/awscli/customizations/cliinputjson.py
/lib/python2.7/site-packages/awscli/customizations/cliinputjson.pyc
/lib/python2.7/site-packages/awscli/customizations/cliinputjson.pyo
/lib/python2.7/site-packages/awscli/customizations/cloudsearch.py
/lib/python2.7/site-packages/awscli/customizations/cloudsearch.pyc
/lib/python2.7/site-packages/awscli/customizations/cloudsearch.pyo
/lib/python2.7/site-packages/awscli/customizations/cloudsearchdomain.py
/lib/python2.7/site-packages/awscli/customizations/cloudsearchdomain.pyc
/lib/python2.7/site-packages/awscli/customizations/cloudsearchdomain.pyo
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/__init__.py
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/subscribe.py
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/subscribe.pyc
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/subscribe.pyo
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/utils.py
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/utils.pyc
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/utils.pyo
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/validation.py
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/validation.pyc
/lib/python2.7/site-packages/awscli/customizations/cloudtrail/validation.pyo
/lib/python2.7/site-packages/awscli/customizations/codecommit.py
/lib/python2.7/site-packages/awscli/customizations/codecommit.pyc
/lib/python2.7/site-packages/awscli/customizations/codecommit.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/__init__.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/codedeploy.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/codedeploy.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/codedeploy.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/deregister.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/deregister.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/deregister.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/install.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/install.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/install.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/locationargs.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/locationargs.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/locationargs.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/push.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/push.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/push.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/register.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/register.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/register.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/systems.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/systems.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/systems.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/uninstall.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/uninstall.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/uninstall.pyo
/lib/python2.7/site-packages/awscli/customizations/codedeploy/utils.py
/lib/python2.7/site-packages/awscli/customizations/codedeploy/utils.pyc
/lib/python2.7/site-packages/awscli/customizations/codedeploy/utils.pyo
/lib/python2.7/site-packages/awscli/customizations/commands.py
/lib/python2.7/site-packages/awscli/customizations/commands.pyc
/lib/python2.7/site-packages/awscli/customizations/commands.pyo
/lib/python2.7/site-packages/awscli/customizations/configservice/__init__.py
/lib/python2.7/site-packages/awscli/customizations/configservice/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/configservice/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/configservice/getstatus.py
/lib/python2.7/site-packages/awscli/customizations/configservice/getstatus.pyc
/lib/python2.7/site-packages/awscli/customizations/configservice/getstatus.pyo
/lib/python2.7/site-packages/awscli/customizations/configservice/putconfigurationrecorder.py
/lib/python2.7/site-packages/awscli/customizations/configservice/putconfigurationrecorder.pyc
/lib/python2.7/site-packages/awscli/customizations/configservice/putconfigurationrecorder.pyo
/lib/python2.7/site-packages/awscli/customizations/configservice/rename_cmd.py
/lib/python2.7/site-packages/awscli/customizations/configservice/rename_cmd.pyc
/lib/python2.7/site-packages/awscli/customizations/configservice/rename_cmd.pyo
/lib/python2.7/site-packages/awscli/customizations/configservice/subscribe.py
/lib/python2.7/site-packages/awscli/customizations/configservice/subscribe.pyc
/lib/python2.7/site-packages/awscli/customizations/configservice/subscribe.pyo
/lib/python2.7/site-packages/awscli/customizations/configure.py
/lib/python2.7/site-packages/awscli/customizations/configure.pyc
/lib/python2.7/site-packages/awscli/customizations/configure.pyo
/lib/python2.7/site-packages/awscli/customizations/datapipeline/__init__.py
/lib/python2.7/site-packages/awscli/customizations/datapipeline/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/datapipeline/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/datapipeline/constants.py
/lib/python2.7/site-packages/awscli/customizations/datapipeline/constants.pyc
/lib/python2.7/site-packages/awscli/customizations/datapipeline/constants.pyo
/lib/python2.7/site-packages/awscli/customizations/datapipeline/createdefaultroles.py
/lib/python2.7/site-packages/awscli/customizations/datapipeline/createdefaultroles.pyc
/lib/python2.7/site-packages/awscli/customizations/datapipeline/createdefaultroles.pyo
/lib/python2.7/site-packages/awscli/customizations/datapipeline/translator.py
/lib/python2.7/site-packages/awscli/customizations/datapipeline/translator.pyc
/lib/python2.7/site-packages/awscli/customizations/datapipeline/translator.pyo
/lib/python2.7/site-packages/awscli/customizations/ec2addcount.py
/lib/python2.7/site-packages/awscli/customizations/ec2addcount.pyc
/lib/python2.7/site-packages/awscli/customizations/ec2addcount.pyo
/lib/python2.7/site-packages/awscli/customizations/ec2bundleinstance.py
/lib/python2.7/site-packages/awscli/customizations/ec2bundleinstance.pyc
/lib/python2.7/site-packages/awscli/customizations/ec2bundleinstance.pyo
/lib/python2.7/site-packages/awscli/customizations/ec2decryptpassword.py
/lib/python2.7/site-packages/awscli/customizations/ec2decryptpassword.pyc
/lib/python2.7/site-packages/awscli/customizations/ec2decryptpassword.pyo
/lib/python2.7/site-packages/awscli/customizations/ec2protocolarg.py
/lib/python2.7/site-packages/awscli/customizations/ec2protocolarg.pyc
/lib/python2.7/site-packages/awscli/customizations/ec2protocolarg.pyo
/lib/python2.7/site-packages/awscli/customizations/ec2runinstances.py
/lib/python2.7/site-packages/awscli/customizations/ec2runinstances.pyc
/lib/python2.7/site-packages/awscli/customizations/ec2runinstances.pyo
/lib/python2.7/site-packages/awscli/customizations/ec2secgroupsimplify.py
/lib/python2.7/site-packages/awscli/customizations/ec2secgroupsimplify.pyc
/lib/python2.7/site-packages/awscli/customizations/ec2secgroupsimplify.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/__init__.py
/lib/python2.7/site-packages/awscli/customizations/emr/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/addinstancegroups.py
/lib/python2.7/site-packages/awscli/customizations/emr/addinstancegroups.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/addinstancegroups.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/addsteps.py
/lib/python2.7/site-packages/awscli/customizations/emr/addsteps.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/addsteps.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/addtags.py
/lib/python2.7/site-packages/awscli/customizations/emr/addtags.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/addtags.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/applicationutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/applicationutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/applicationutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/argumentschema.py
/lib/python2.7/site-packages/awscli/customizations/emr/argumentschema.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/argumentschema.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/command.py
/lib/python2.7/site-packages/awscli/customizations/emr/command.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/command.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/config.py
/lib/python2.7/site-packages/awscli/customizations/emr/config.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/config.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/configutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/configutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/configutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/constants.py
/lib/python2.7/site-packages/awscli/customizations/emr/constants.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/constants.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/createcluster.py
/lib/python2.7/site-packages/awscli/customizations/emr/createcluster.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/createcluster.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/createdefaultroles.py
/lib/python2.7/site-packages/awscli/customizations/emr/createdefaultroles.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/createdefaultroles.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/describecluster.py
/lib/python2.7/site-packages/awscli/customizations/emr/describecluster.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/describecluster.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/emr.py
/lib/python2.7/site-packages/awscli/customizations/emr/emr.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/emr.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/emrfsutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/emrfsutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/emrfsutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/emrutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/emrutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/emrutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/exceptions.py
/lib/python2.7/site-packages/awscli/customizations/emr/exceptions.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/exceptions.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/hbase.py
/lib/python2.7/site-packages/awscli/customizations/emr/hbase.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/hbase.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/hbaseutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/hbaseutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/hbaseutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/helptext.py
/lib/python2.7/site-packages/awscli/customizations/emr/helptext.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/helptext.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/installapplications.py
/lib/python2.7/site-packages/awscli/customizations/emr/installapplications.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/installapplications.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/instancegroupsutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/instancegroupsutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/instancegroupsutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/listclusters.py
/lib/python2.7/site-packages/awscli/customizations/emr/listclusters.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/listclusters.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/modifyclusterattributes.py
/lib/python2.7/site-packages/awscli/customizations/emr/modifyclusterattributes.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/modifyclusterattributes.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/ssh.py
/lib/python2.7/site-packages/awscli/customizations/emr/ssh.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/ssh.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/sshutils.py
/lib/python2.7/site-packages/awscli/customizations/emr/sshutils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/sshutils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/steputils.py
/lib/python2.7/site-packages/awscli/customizations/emr/steputils.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/steputils.pyo
/lib/python2.7/site-packages/awscli/customizations/emr/terminateclusters.py
/lib/python2.7/site-packages/awscli/customizations/emr/terminateclusters.pyc
/lib/python2.7/site-packages/awscli/customizations/emr/terminateclusters.pyo
/lib/python2.7/site-packages/awscli/customizations/flatten.py
/lib/python2.7/site-packages/awscli/customizations/flatten.pyc
/lib/python2.7/site-packages/awscli/customizations/flatten.pyo
/lib/python2.7/site-packages/awscli/customizations/generatecliskeleton.py
/lib/python2.7/site-packages/awscli/customizations/generatecliskeleton.pyc
/lib/python2.7/site-packages/awscli/customizations/generatecliskeleton.pyo
/lib/python2.7/site-packages/awscli/customizations/globalargs.py
/lib/python2.7/site-packages/awscli/customizations/globalargs.pyc
/lib/python2.7/site-packages/awscli/customizations/globalargs.pyo
/lib/python2.7/site-packages/awscli/customizations/iamvirtmfa.py
/lib/python2.7/site-packages/awscli/customizations/iamvirtmfa.pyc
/lib/python2.7/site-packages/awscli/customizations/iamvirtmfa.pyo
/lib/python2.7/site-packages/awscli/customizations/iot.py
/lib/python2.7/site-packages/awscli/customizations/iot.pyc
/lib/python2.7/site-packages/awscli/customizations/iot.pyo
/lib/python2.7/site-packages/awscli/customizations/iot_data.py
/lib/python2.7/site-packages/awscli/customizations/iot_data.pyc
/lib/python2.7/site-packages/awscli/customizations/iot_data.pyo
/lib/python2.7/site-packages/awscli/customizations/kms.py
/lib/python2.7/site-packages/awscli/customizations/kms.pyc
/lib/python2.7/site-packages/awscli/customizations/kms.pyo
/lib/python2.7/site-packages/awscli/customizations/opsworks.py
/lib/python2.7/site-packages/awscli/customizations/opsworks.pyc
/lib/python2.7/site-packages/awscli/customizations/opsworks.pyo
/lib/python2.7/site-packages/awscli/customizations/paginate.py
/lib/python2.7/site-packages/awscli/customizations/paginate.pyc
/lib/python2.7/site-packages/awscli/customizations/paginate.pyo
/lib/python2.7/site-packages/awscli/customizations/preview.py
/lib/python2.7/site-packages/awscli/customizations/preview.pyc
/lib/python2.7/site-packages/awscli/customizations/preview.pyo
/lib/python2.7/site-packages/awscli/customizations/putmetricdata.py
/lib/python2.7/site-packages/awscli/customizations/putmetricdata.pyc
/lib/python2.7/site-packages/awscli/customizations/putmetricdata.pyo
/lib/python2.7/site-packages/awscli/customizations/rds.py
/lib/python2.7/site-packages/awscli/customizations/rds.pyc
/lib/python2.7/site-packages/awscli/customizations/rds.pyo
/lib/python2.7/site-packages/awscli/customizations/removals.py
/lib/python2.7/site-packages/awscli/customizations/removals.pyc
/lib/python2.7/site-packages/awscli/customizations/removals.pyo
/lib/python2.7/site-packages/awscli/customizations/route53.py
/lib/python2.7/site-packages/awscli/customizations/route53.pyc
/lib/python2.7/site-packages/awscli/customizations/route53.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/__init__.py
/lib/python2.7/site-packages/awscli/customizations/s3/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/comparator.py
/lib/python2.7/site-packages/awscli/customizations/s3/comparator.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/comparator.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/executor.py
/lib/python2.7/site-packages/awscli/customizations/s3/executor.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/executor.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/fileformat.py
/lib/python2.7/site-packages/awscli/customizations/s3/fileformat.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/fileformat.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/filegenerator.py
/lib/python2.7/site-packages/awscli/customizations/s3/filegenerator.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/filegenerator.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.py
/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/fileinfobuilder.py
/lib/python2.7/site-packages/awscli/customizations/s3/fileinfobuilder.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/fileinfobuilder.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/filters.py
/lib/python2.7/site-packages/awscli/customizations/s3/filters.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/filters.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/s3.py
/lib/python2.7/site-packages/awscli/customizations/s3/s3.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/s3.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.py
/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py
/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/__init__.py
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/__init__.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/__init__.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/base.py
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/base.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/base.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/delete.py
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/delete.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/delete.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/exacttimestamps.py
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/exacttimestamps.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/exacttimestamps.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/register.py
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/register.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/register.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/sizeonly.py
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/sizeonly.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/syncstrategy/sizeonly.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/tasks.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/tasks.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/transferconfig.py
/lib/python2.7/site-packages/awscli/customizations/s3/transferconfig.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/transferconfig.pyo
/lib/python2.7/site-packages/awscli/customizations/s3/utils.py
/lib/python2.7/site-packages/awscli/customizations/s3/utils.pyc
/lib/python2.7/site-packages/awscli/customizations/s3/utils.pyo
/lib/python2.7/site-packages/awscli/customizations/s3endpoint.py
/lib/python2.7/site-packages/awscli/customizations/s3endpoint.pyc
/lib/python2.7/site-packages/awscli/customizations/s3endpoint.pyo
/lib/python2.7/site-packages/awscli/customizations/s3errormsg.py
/lib/python2.7/site-packages/awscli/customizations/s3errormsg.pyc
/lib/python2.7/site-packages/awscli/customizations/s3errormsg.pyo
/lib/python2.7/site-packages/awscli/customizations/scalarparse.py
/lib/python2.7/site-packages/awscli/customizations/scalarparse.pyc
/lib/python2.7/site-packages/awscli/customizations/scalarparse.pyo
/lib/python2.7/site-packages/awscli/customizations/sessendemail.py
/lib/python2.7/site-packages/awscli/customizations/sessendemail.pyc
/lib/python2.7/site-packages/awscli/customizations/sessendemail.pyo
/lib/python2.7/site-packages/awscli/customizations/streamingoutputarg.py
/lib/python2.7/site-packages/awscli/customizations/streamingoutputarg.pyc
/lib/python2.7/site-packages/awscli/customizations/streamingoutputarg.pyo
/lib/python2.7/site-packages/awscli/customizations/toplevelbool.py
/lib/python2.7/site-packages/awscli/customizations/toplevelbool.pyc
/lib/python2.7/site-packages/awscli/customizations/toplevelbool.pyo
/lib/python2.7/site-packages/awscli/customizations/utils.py
/lib/python2.7/site-packages/awscli/customizations/utils.pyc
/lib/python2.7/site-packages/awscli/customizations/utils.pyo
/lib/python2.7/site-packages/awscli/customizations/waiters.py
/lib/python2.7/site-packages/awscli/customizations/waiters.pyc
/lib/python2.7/site-packages/awscli/customizations/waiters.pyo
/lib/python2.7/site-packages/awscli/data/cli.json
/lib/python2.7/site-packages/awscli/errorhandler.py
/lib/python2.7/site-packages/awscli/errorhandler.pyc
/lib/python2.7/site-packages/awscli/errorhandler.pyo
/lib/python2.7/site-packages/awscli/examples/autoscaling/attach-instances.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/attach-load-balancers.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/complete-lifecycle-action.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/create-auto-scaling-group.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/create-launch-configuration.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/create-or-update-tags.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-auto-scaling-group.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-launch-configuration.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-lifecycle-hook.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-notification-configuration.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-policy.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-scheduled-action.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/delete-tags.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-account-limits.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-adjustment-types.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-auto-scaling-groups.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-auto-scaling-instances.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-auto-scaling-notification-types.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-launch-configurations.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-lifecycle-hook-types.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-lifecycle-hooks.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-load-balancers.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-metric-collection-types.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-notification-configurations.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-policies.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-scaling-activities.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-scaling-process-types.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-scheduled-actions.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-tags.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/describe-termination-policy-types.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/detach-instances.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/detach-load-balancers.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/disable-metrics-collection.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/enable-metrics-collection.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/enter-standby.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/execute-policy.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/exit-standby.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/put-lifecycle-hook.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/put-notification-configuration.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/put-scaling-policy.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/put-scheduled-update-group-action.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/record-lifecycle-action-heartbeat.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/resume-processes.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/set-desired-capacity.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/set-instance-health.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/suspend-processes.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/terminate-instance-in-auto-scaling-group.rst
/lib/python2.7/site-packages/awscli/examples/autoscaling/update-auto-scaling-group.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/cancel-update-stack.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/create-stack.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/describe-stacks.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/get-template.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/list-stacks.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/update-stack.rst
/lib/python2.7/site-packages/awscli/examples/cloudformation/validate-template.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/create-distribution.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/create-invalidation.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/delete-distribution.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/get-distribution-config.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/get-distribution.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/get-invalidation.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/list-distributions.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/list-invalidations.rst
/lib/python2.7/site-packages/awscli/examples/cloudfront/update-distribution.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/delete-alarms.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/describe-alarm-history.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/describe-alarms-for-metric.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/describe-alarms.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/disable-alarm-actions.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/enable-alarm-actions.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/get-metric-statistics.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/list-metrics.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/put-metric-alarm.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/put-metric-data.rst
/lib/python2.7/site-packages/awscli/examples/cloudwatch/set-alarm-state.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/batch-get-repositories.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/create-branch.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/create-repository.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/delete-branch.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/delete-repository.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/get-branch.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/get-repository.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/list-branches.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/list-repositories.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/update-default-branch.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/update-repository-description.rst
/lib/python2.7/site-packages/awscli/examples/codecommit/update-repository-name.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/acknowledge-job.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/create-custom-action-type.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/create-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/delete-custom-action-type.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/delete-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/disable-stage-transition.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/enable-stage-transition.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/get-job-details.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/get-pipeline-state.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/get-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/list-action-types.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/list-pipelines.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/poll-for-jobs.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/start-pipeline-execution.rst
/lib/python2.7/site-packages/awscli/examples/codepipeline/update-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/configure/_description.rst
/lib/python2.7/site-packages/awscli/examples/configure/get/_description.rst
/lib/python2.7/site-packages/awscli/examples/configure/get/_examples.rst
/lib/python2.7/site-packages/awscli/examples/configure/set/_description.rst
/lib/python2.7/site-packages/awscli/examples/configure/set/_examples.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/activate-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/add-tags.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/create-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/deactivate-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/delete-pipeline.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/describe-pipelines.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/get-pipeline-definition.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/list-pipelines.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/list-runs.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/put-pipeline-definition.rst
/lib/python2.7/site-packages/awscli/examples/datapipeline/remove-tags.rst
/lib/python2.7/site-packages/awscli/examples/deploy/add-tags-to-on-premises-instances.rst
/lib/python2.7/site-packages/awscli/examples/deploy/batch-get-applications.rst
/lib/python2.7/site-packages/awscli/examples/deploy/batch-get-deployments.rst
/lib/python2.7/site-packages/awscli/examples/deploy/batch-get-on-premises-instances.rst
/lib/python2.7/site-packages/awscli/examples/deploy/create-application.rst
/lib/python2.7/site-packages/awscli/examples/deploy/create-deployment-config.rst
/lib/python2.7/site-packages/awscli/examples/deploy/create-deployment-group.rst
/lib/python2.7/site-packages/awscli/examples/deploy/create-deployment.rst
/lib/python2.7/site-packages/awscli/examples/deploy/delete-application.rst
/lib/python2.7/site-packages/awscli/examples/deploy/delete-deployment-config.rst
/lib/python2.7/site-packages/awscli/examples/deploy/delete-deployment-group.rst
/lib/python2.7/site-packages/awscli/examples/deploy/deregister-on-premises-instance.rst
/lib/python2.7/site-packages/awscli/examples/deploy/deregister.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-application-revision.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-application.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-deployment-config.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-deployment-group.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-deployment-instance.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-deployment.rst
/lib/python2.7/site-packages/awscli/examples/deploy/get-on-premises-instance.rst
/lib/python2.7/site-packages/awscli/examples/deploy/install.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-application-revisions.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-applications.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-deployment-configs.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-deployment-groups.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-deployment-instances.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-deployments.rst
/lib/python2.7/site-packages/awscli/examples/deploy/list-on-premises-instances.rst
/lib/python2.7/site-packages/awscli/examples/deploy/push.rst
/lib/python2.7/site-packages/awscli/examples/deploy/register-application-revision.rst
/lib/python2.7/site-packages/awscli/examples/deploy/register-on-premises-instance.rst
/lib/python2.7/site-packages/awscli/examples/deploy/register.rst
/lib/python2.7/site-packages/awscli/examples/deploy/remove-tags-from-on-premises-instances.rst
/lib/python2.7/site-packages/awscli/examples/deploy/stop-deployment.rst
/lib/python2.7/site-packages/awscli/examples/deploy/uninstall.rst
/lib/python2.7/site-packages/awscli/examples/deploy/update-application.rst
/lib/python2.7/site-packages/awscli/examples/deploy/update-deployment-group.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/batch-get-item.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/batch-write-item.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/create-table.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/delete-item.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/delete-table.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/describe-table.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/get-item.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/list-tables.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/put-item.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/query.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/scan.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/update-item.rst
/lib/python2.7/site-packages/awscli/examples/dynamodb/update-table.rst
/lib/python2.7/site-packages/awscli/examples/ec2/accept-vpc-peering-connection.rst
/lib/python2.7/site-packages/awscli/examples/ec2/allocate-address.rst
/lib/python2.7/site-packages/awscli/examples/ec2/assign-private-ip-addresses.rst
/lib/python2.7/site-packages/awscli/examples/ec2/associate-address.rst
/lib/python2.7/site-packages/awscli/examples/ec2/associate-dhcp-options.rst
/lib/python2.7/site-packages/awscli/examples/ec2/associate-route-table.rst
/lib/python2.7/site-packages/awscli/examples/ec2/attach-classic-link-vpc.rst
/lib/python2.7/site-packages/awscli/examples/ec2/attach-internet-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/attach-network-interface.rst
/lib/python2.7/site-packages/awscli/examples/ec2/attach-volume.rst
/lib/python2.7/site-packages/awscli/examples/ec2/attach-vpn-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/authorize-security-group-egress.rst
/lib/python2.7/site-packages/awscli/examples/ec2/authorize-security-group-ingress.rst
/lib/python2.7/site-packages/awscli/examples/ec2/bundle-instance.rst
/lib/python2.7/site-packages/awscli/examples/ec2/cancel-bundle-task.rst
/lib/python2.7/site-packages/awscli/examples/ec2/cancel-conversion-task.rst
/lib/python2.7/site-packages/awscli/examples/ec2/cancel-export-task.rst
/lib/python2.7/site-packages/awscli/examples/ec2/cancel-spot-fleet-requests.rst
/lib/python2.7/site-packages/awscli/examples/ec2/cancel-spot-instance-requests.rst
/lib/python2.7/site-packages/awscli/examples/ec2/confirm-product-instance.rst
/lib/python2.7/site-packages/awscli/examples/ec2/copy-image.rst
/lib/python2.7/site-packages/awscli/examples/ec2/copy-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-customer-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-dhcp-options.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-flow-logs.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-image.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-instance-export-task.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-internet-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-key-pair.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-network-acl-entry.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-network-acl.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-network-interface.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-placement-group.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-route-table.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-route.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-security-group.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-spot-datafeed-subscription.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-subnet.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-tags.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-volume.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-vpc-endpoint.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-vpc-peering-connection.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-vpc.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-vpn-connection-route.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-vpn-connection.rst
/lib/python2.7/site-packages/awscli/examples/ec2/create-vpn-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-customer-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-dhcp-options.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-flow-logs.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-internet-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-key-pair.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-network-acl-entry.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-network-acl.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-network-interface.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-placement-group.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-route-table.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-route.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-security-group.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-spot-datafeed-subscription.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-subnet.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-tags.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-volume.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-vpc-endpoints.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-vpc-peering-connection.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-vpc.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-vpn-connection-route.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-vpn-connection.rst
/lib/python2.7/site-packages/awscli/examples/ec2/delete-vpn-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/deregister-image.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-account-attributes.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-addresses.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-availability-zones.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-bundle-tasks.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-classic-link-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-conversion-tasks.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-customer-gateways.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-dhcp-options.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-export-tasks.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-flow-logs.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-image-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-images.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-instance-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-instance-status.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-internet-gateways.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-key-pairs.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-moving-addresses.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-network-acls.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-network-interface-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-network-interfaces.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-placement-groups.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-prefix-lists.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-regions.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-reserved-instances-modifications.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-reserved-instances-offerings.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-reserved-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-route-tables.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-security-groups.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-snapshot-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-snapshots.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-spot-datafeed-subscription.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-spot-fleet-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-spot-fleet-request-history.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-spot-fleet-requests.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-spot-instance-requests.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-spot-price-history.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-subnets.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-tags.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-volume-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-volume-status.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-volumes.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpc-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpc-classic-link.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpc-endpoint-services.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpc-endpoints.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpc-peering-connections.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpcs.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpn-connections.rst
/lib/python2.7/site-packages/awscli/examples/ec2/describe-vpn-gateways.rst
/lib/python2.7/site-packages/awscli/examples/ec2/detach-classic-link-vpc.rst
/lib/python2.7/site-packages/awscli/examples/ec2/detach-internet-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/detach-network-interface.rst
/lib/python2.7/site-packages/awscli/examples/ec2/detach-volume.rst
/lib/python2.7/site-packages/awscli/examples/ec2/detach-vpn-gateway.rst
/lib/python2.7/site-packages/awscli/examples/ec2/disable-vgw-route-propagation.rst
/lib/python2.7/site-packages/awscli/examples/ec2/disable-vpc-classic-link.rst
/lib/python2.7/site-packages/awscli/examples/ec2/disassociate-address.rst
/lib/python2.7/site-packages/awscli/examples/ec2/disassociate-route-table.rst
/lib/python2.7/site-packages/awscli/examples/ec2/enable-vgw-route-propagation.rst
/lib/python2.7/site-packages/awscli/examples/ec2/enable-vpc-classic-link.rst
/lib/python2.7/site-packages/awscli/examples/ec2/get-console-output.rst
/lib/python2.7/site-packages/awscli/examples/ec2/get-password-data.rst
/lib/python2.7/site-packages/awscli/examples/ec2/import-key-pair.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-image-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-instance-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-network-interface-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-reserved-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-snapshot-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-spot-fleet-request.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-subnet-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-volume-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-vpc-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/modify-vpc-endpoint.rst
/lib/python2.7/site-packages/awscli/examples/ec2/monitor-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/move-address-to-vpc.rst
/lib/python2.7/site-packages/awscli/examples/ec2/purchase-reserved-instances-offering.rst
/lib/python2.7/site-packages/awscli/examples/ec2/reboot-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/register-image.rst
/lib/python2.7/site-packages/awscli/examples/ec2/reject-vpc-peering-connection.rst
/lib/python2.7/site-packages/awscli/examples/ec2/release-address.rst
/lib/python2.7/site-packages/awscli/examples/ec2/replace-network-acl-association.rst
/lib/python2.7/site-packages/awscli/examples/ec2/replace-network-acl-entry.rst
/lib/python2.7/site-packages/awscli/examples/ec2/replace-route-table-association.rst
/lib/python2.7/site-packages/awscli/examples/ec2/replace-route.rst
/lib/python2.7/site-packages/awscli/examples/ec2/report-instance-status.rst
/lib/python2.7/site-packages/awscli/examples/ec2/request-spot-fleet.rst
/lib/python2.7/site-packages/awscli/examples/ec2/request-spot-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/reset-image-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/reset-instance-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/reset-snapshot-attribute.rst
/lib/python2.7/site-packages/awscli/examples/ec2/restore-address-to-classic.rst
/lib/python2.7/site-packages/awscli/examples/ec2/revoke-security-group-egress.rst
/lib/python2.7/site-packages/awscli/examples/ec2/revoke-security-group-ingress.rst
/lib/python2.7/site-packages/awscli/examples/ec2/run-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/start-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/stop-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/terminate-instances.rst
/lib/python2.7/site-packages/awscli/examples/ec2/unassign-private-ip-addresses.rst
/lib/python2.7/site-packages/awscli/examples/ec2/unmonitor-instances.rst
/lib/python2.7/site-packages/awscli/examples/ecs/create-cluster.rst
/lib/python2.7/site-packages/awscli/examples/ecs/create-service.rst
/lib/python2.7/site-packages/awscli/examples/ecs/delete-cluster.rst
/lib/python2.7/site-packages/awscli/examples/ecs/delete-service.rst
/lib/python2.7/site-packages/awscli/examples/ecs/deregister-container-instance.rst
/lib/python2.7/site-packages/awscli/examples/ecs/deregister-task-definition.rst
/lib/python2.7/site-packages/awscli/examples/ecs/describe-clusters.rst
/lib/python2.7/site-packages/awscli/examples/ecs/describe-container-instances.rst
/lib/python2.7/site-packages/awscli/examples/ecs/describe-services.rst
/lib/python2.7/site-packages/awscli/examples/ecs/describe-task-definition.rst
/lib/python2.7/site-packages/awscli/examples/ecs/describe-tasks.rst
/lib/python2.7/site-packages/awscli/examples/ecs/list-clusters.rst
/lib/python2.7/site-packages/awscli/examples/ecs/list-container-instances.rst
/lib/python2.7/site-packages/awscli/examples/ecs/list-services.rst
/lib/python2.7/site-packages/awscli/examples/ecs/list-task-definition-families.rst
/lib/python2.7/site-packages/awscli/examples/ecs/list-task-definitions.rst
/lib/python2.7/site-packages/awscli/examples/ecs/list-tasks.rst
/lib/python2.7/site-packages/awscli/examples/ecs/register-task-definition.rst
/lib/python2.7/site-packages/awscli/examples/ecs/run-task.rst
/lib/python2.7/site-packages/awscli/examples/ecs/update-container-agent.rst
/lib/python2.7/site-packages/awscli/examples/ecs/update-service.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/abort-environment-update.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/check-dns-availability.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/create-application-version.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/create-application.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/create-configuration-template.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/create-environment.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/create-storage-location.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/delete-application-version.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/delete-application.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/delete-configuration-template.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/delete-environment-configuration.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-application-versions.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-applications.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-configuration-options.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-configuration-settings.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-environment-health.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-environment-resources.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-environments.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-events.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/describe-instances-health.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/list-available-solution-stacks.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/rebuild-environment.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/request-environment-info.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/restart-app-server.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/retrieve-environment-info.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/swap-environment-cnames.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/terminate-environment.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/update-application-version.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/update-application.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/update-configuration-template.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/update-environment.rst
/lib/python2.7/site-packages/awscli/examples/elasticbeanstalk/validate-configuration-settings.rst
/lib/python2.7/site-packages/awscli/examples/elb/add-tags.rst
/lib/python2.7/site-packages/awscli/examples/elb/apply-security-groups-to-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/attach-load-balancer-to-subnets.rst
/lib/python2.7/site-packages/awscli/examples/elb/configure-health-check.rst
/lib/python2.7/site-packages/awscli/examples/elb/create-app-cookie-stickiness-policy.rst
/lib/python2.7/site-packages/awscli/examples/elb/create-lb-cookie-stickiness-policy.rst
/lib/python2.7/site-packages/awscli/examples/elb/create-load-balancer-listeners.rst
/lib/python2.7/site-packages/awscli/examples/elb/create-load-balancer-policy.rst
/lib/python2.7/site-packages/awscli/examples/elb/create-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/delete-load-balancer-listeners.rst
/lib/python2.7/site-packages/awscli/examples/elb/delete-load-balancer-policy.rst
/lib/python2.7/site-packages/awscli/examples/elb/delete-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/deregister-instances-from-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/describe-instance-health.rst
/lib/python2.7/site-packages/awscli/examples/elb/describe-load-balancer-attributes.rst
/lib/python2.7/site-packages/awscli/examples/elb/describe-load-balancer-policies.rst
/lib/python2.7/site-packages/awscli/examples/elb/describe-load-balancer-policy-types.rst
/lib/python2.7/site-packages/awscli/examples/elb/describe-load-balancers.rst
/lib/python2.7/site-packages/awscli/examples/elb/describe-tags.rst
/lib/python2.7/site-packages/awscli/examples/elb/detach-load-balancer-from-subnets.rst
/lib/python2.7/site-packages/awscli/examples/elb/disable-availability-zones-for-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/enable-availability-zones-for-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/modify-load-balancer-attributes.rst
/lib/python2.7/site-packages/awscli/examples/elb/register-instances-with-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/elb/remove-tags.rst
/lib/python2.7/site-packages/awscli/examples/elb/set-load-balancer-listener-ssl-certificate.rst
/lib/python2.7/site-packages/awscli/examples/elb/set-load-balancer-policies-for-backend-server.rst
/lib/python2.7/site-packages/awscli/examples/elb/set-load-balancer-policies-of-listener.rst
/lib/python2.7/site-packages/awscli/examples/emr/add-steps.rst
/lib/python2.7/site-packages/awscli/examples/emr/add-tags.rst
/lib/python2.7/site-packages/awscli/examples/emr/create-cluster-examples.rst
/lib/python2.7/site-packages/awscli/examples/emr/create-cluster-synopsis.rst
/lib/python2.7/site-packages/awscli/examples/emr/create-default-roles.rst
/lib/python2.7/site-packages/awscli/examples/emr/describe-cluster.rst
/lib/python2.7/site-packages/awscli/examples/emr/describe-step.rst
/lib/python2.7/site-packages/awscli/examples/emr/get.rst
/lib/python2.7/site-packages/awscli/examples/emr/list-clusters.rst
/lib/python2.7/site-packages/awscli/examples/emr/list-instances.rst
/lib/python2.7/site-packages/awscli/examples/emr/list-steps.rst
/lib/python2.7/site-packages/awscli/examples/emr/modify-cluster-attributes.rst
/lib/python2.7/site-packages/awscli/examples/emr/put.rst
/lib/python2.7/site-packages/awscli/examples/emr/remove-tags.rst
/lib/python2.7/site-packages/awscli/examples/emr/schedule-hbase-backup.rst
/lib/python2.7/site-packages/awscli/examples/emr/socks.rst
/lib/python2.7/site-packages/awscli/examples/emr/ssh.rst
/lib/python2.7/site-packages/awscli/examples/emr/wait.rst
/lib/python2.7/site-packages/awscli/examples/glacier/abort-multipart-upload.rst
/lib/python2.7/site-packages/awscli/examples/glacier/add-tags-to-vault.rst
/lib/python2.7/site-packages/awscli/examples/glacier/complete-multipart-upload.rst
/lib/python2.7/site-packages/awscli/examples/glacier/create-vault.rst
/lib/python2.7/site-packages/awscli/examples/glacier/delete-vault.rst
/lib/python2.7/site-packages/awscli/examples/glacier/describe-job.rst
/lib/python2.7/site-packages/awscli/examples/glacier/describe-vault.rst
/lib/python2.7/site-packages/awscli/examples/glacier/get-data-retrieval-policy.rst
/lib/python2.7/site-packages/awscli/examples/glacier/get-job-output.rst
/lib/python2.7/site-packages/awscli/examples/glacier/get-vault-notifications.rst
/lib/python2.7/site-packages/awscli/examples/glacier/initiate-job.rst
/lib/python2.7/site-packages/awscli/examples/glacier/initiate-multipart-upload.rst
/lib/python2.7/site-packages/awscli/examples/glacier/list-jobs.rst
/lib/python2.7/site-packages/awscli/examples/glacier/list-multipart-uploads.rst
/lib/python2.7/site-packages/awscli/examples/glacier/list-parts.rst
/lib/python2.7/site-packages/awscli/examples/glacier/list-tags-for-vault.rst
/lib/python2.7/site-packages/awscli/examples/glacier/list-vaults.rst
/lib/python2.7/site-packages/awscli/examples/glacier/remove-tags-from-vault.rst
/lib/python2.7/site-packages/awscli/examples/glacier/set-data-retrieval-policy.rst
/lib/python2.7/site-packages/awscli/examples/glacier/set-vault-notifications.rst
/lib/python2.7/site-packages/awscli/examples/glacier/upload-archive.rst
/lib/python2.7/site-packages/awscli/examples/glacier/upload-multipart-part.rst
/lib/python2.7/site-packages/awscli/examples/iam/add-client-id-to-open-id-connect-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/add-role-to-instance-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/add-user-to-group.rst
/lib/python2.7/site-packages/awscli/examples/iam/attach-group-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/attach-role-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/attach-user-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/change-password.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-access-key.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-account-alias.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-group.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-instance-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-login-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-open-id-connect-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-policy-version.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-role.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-saml-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-user.rst
/lib/python2.7/site-packages/awscli/examples/iam/create-virtual-mfa-device.rst
/lib/python2.7/site-packages/awscli/examples/iam/deactivate-mfa-device.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-access-key.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-account-alias.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-account-password-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-group-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-group.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-instance-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-login-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-open-id-connect-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-policy-version.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-role-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-role.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-saml-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-signing-certificate.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-user-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-user.rst
/lib/python2.7/site-packages/awscli/examples/iam/delete-virtual-mfa-device.rst
/lib/python2.7/site-packages/awscli/examples/iam/detach-group-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/detach-role-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/detach-user-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/enable-mfa-device.rst
/lib/python2.7/site-packages/awscli/examples/iam/generate-credential-report.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-access-key-last-used.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-account-authorization-details.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-account-password-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-account-summary.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-credential-report.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-group-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-group.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-instance-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-login-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-open-id-connect-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-policy-version.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-role-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-role.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-saml-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-user-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/get-user.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-access-keys.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-account-aliases.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-attached-group-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-attached-role-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-attached-user-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-entities-for-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-group-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-groups-for-user.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-groups.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-instance-profiles-for-role.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-instance-profiles.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-mfa-devices.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-open-id-connect-providers.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-policy-versions.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-role-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-roles.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-saml-providers.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-signing-certificates.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-user-policies.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-users.rst
/lib/python2.7/site-packages/awscli/examples/iam/list-virtual-mfa-devices.rst
/lib/python2.7/site-packages/awscli/examples/iam/put-group-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/put-role-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/put-user-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/remove-client-id-from-open-id-connect-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/remove-role-from-instance-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/remove-user-from-group.rst
/lib/python2.7/site-packages/awscli/examples/iam/resync-mfa-device.rst
/lib/python2.7/site-packages/awscli/examples/iam/set-default-policy-version.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-access-key.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-account-password-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-assume-role-policy.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-group.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-login-profile.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-open-id-connect-provider-thumbprint.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-saml-provider.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-signing-certificate.rst
/lib/python2.7/site-packages/awscli/examples/iam/update-user.rst
/lib/python2.7/site-packages/awscli/examples/iam/upload-server-certificate.rst
/lib/python2.7/site-packages/awscli/examples/iam/upload-signing-certificate.rst
/lib/python2.7/site-packages/awscli/examples/importexport/cancel-job.rst
/lib/python2.7/site-packages/awscli/examples/importexport/create-job.rst
/lib/python2.7/site-packages/awscli/examples/importexport/get-shipping-label.rst
/lib/python2.7/site-packages/awscli/examples/importexport/get-status.rst
/lib/python2.7/site-packages/awscli/examples/importexport/list-jobs.rst
/lib/python2.7/site-packages/awscli/examples/importexport/update-job.rst
/lib/python2.7/site-packages/awscli/examples/iot/create-certificate-from-csr.rst
/lib/python2.7/site-packages/awscli/examples/kms/create-alias.rst
/lib/python2.7/site-packages/awscli/examples/kms/decrypt.rst
/lib/python2.7/site-packages/awscli/examples/kms/encrypt.rst
/lib/python2.7/site-packages/awscli/examples/logs/create-log-group.rst
/lib/python2.7/site-packages/awscli/examples/logs/create-log-stream.rst
/lib/python2.7/site-packages/awscli/examples/logs/delete-log-group.rst
/lib/python2.7/site-packages/awscli/examples/logs/delete-log-stream.rst
/lib/python2.7/site-packages/awscli/examples/logs/delete-retention-policy.rst
/lib/python2.7/site-packages/awscli/examples/logs/describe-log-groups.rst
/lib/python2.7/site-packages/awscli/examples/logs/describe-log-streams.rst
/lib/python2.7/site-packages/awscli/examples/logs/get-log-events.rst
/lib/python2.7/site-packages/awscli/examples/logs/put-log-events.rst
/lib/python2.7/site-packages/awscli/examples/logs/put-retention-policy.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/assign-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/assign-volume.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/associate-elastic-ip.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/attach-elastic-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/create-app.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/create-deployment.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/create-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/create-layer.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/create-stack.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/create-user-profile.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/delete-app.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/delete-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/delete-layer.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/delete-stack.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/delete-user-profile.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/deregister-elastic-ip.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/deregister-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/deregister-rds-db-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/deregister-volume.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-apps.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-commands.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-deployments.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-elastic-ips.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-elastic-load-balancers.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-instances.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-layers.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-load-based-auto-scaling.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-my-user-profile.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-permissions.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-raid-arrays.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-rds-db-instances.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-stack-summary.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-stacks.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-timebased-auto-scaling.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-user-profiles.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/describe-volumes.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/detach-elastic-load-balancer.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/disassociate-elastic-ip.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/get-hostname-suggestion.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/reboot-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/register-elastic-ip.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/register-rds-db-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/register-volume.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/register.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/set-load-based-auto-scaling.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/set-permission.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/set-time-based-auto-scaling.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/start-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/start-stack.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/stop-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/stop-stack.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/unassign-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/unassign-volume.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-app.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-elastic-ip.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-layer.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-my-user-profile.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-rds-db-instance.rst
/lib/python2.7/site-packages/awscli/examples/opsworks/update-volume.rst
/lib/python2.7/site-packages/awscli/examples/rds/add-tag-to-resource.rst
/lib/python2.7/site-packages/awscli/examples/rds/create-db-instance.rst
/lib/python2.7/site-packages/awscli/examples/rds/create-db-security-group.rst
/lib/python2.7/site-packages/awscli/examples/rds/create-option-group.rst
/lib/python2.7/site-packages/awscli/examples/rds/describe-db-instances.rst
/lib/python2.7/site-packages/awscli/examples/rds/download-db-log-file-portion.rst
/lib/python2.7/site-packages/awscli/examples/redshift/authorize-cluster-security-group-ingress.rst
/lib/python2.7/site-packages/awscli/examples/redshift/authorize-snapshot-access.rst
/lib/python2.7/site-packages/awscli/examples/redshift/copy-cluster-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/redshift/create-cluster-parameter-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/create-cluster-security-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/create-cluster-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/redshift/create-cluster-subnet-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/create-cluster.rst
/lib/python2.7/site-packages/awscli/examples/redshift/delete-cluster-parameter-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/delete-cluster-security-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/delete-cluster-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/redshift/delete-cluster-subnet-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/delete-cluster.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-cluster-parameter-groups.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-cluster-parameters.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-cluster-security-groups.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-cluster-snapshots.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-cluster-subnet-groups.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-cluster-versions.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-clusters.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-default-cluster-parameters.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-events.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-orderable-cluster-options.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-reserved-node-offerings.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-reserved-nodes.rst
/lib/python2.7/site-packages/awscli/examples/redshift/describe-resize.rst
/lib/python2.7/site-packages/awscli/examples/redshift/modify-cluster-parameter-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/modify-cluster-subnet-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/modify-cluster.rst
/lib/python2.7/site-packages/awscli/examples/redshift/purchase-reserved-node-offering.rst
/lib/python2.7/site-packages/awscli/examples/redshift/reboot-cluster.rst
/lib/python2.7/site-packages/awscli/examples/redshift/reset-cluster-parameter-group.rst
/lib/python2.7/site-packages/awscli/examples/redshift/restore-from-cluster-snapshot.rst
/lib/python2.7/site-packages/awscli/examples/redshift/revoke-cluster-security-group-ingress.rst
/lib/python2.7/site-packages/awscli/examples/redshift/revoke-snapshot-access.rst
/lib/python2.7/site-packages/awscli/examples/route53/change-resource-record-sets.rst
/lib/python2.7/site-packages/awscli/examples/route53/create-health-check.rst
/lib/python2.7/site-packages/awscli/examples/route53/create-hosted-zone.rst
/lib/python2.7/site-packages/awscli/examples/route53/delete-health-check.rst
/lib/python2.7/site-packages/awscli/examples/route53/delete-hosted-zone.rst
/lib/python2.7/site-packages/awscli/examples/route53/get-change.rst
/lib/python2.7/site-packages/awscli/examples/route53/get-health-check.rst
/lib/python2.7/site-packages/awscli/examples/route53/get-hosted-zone.rst
/lib/python2.7/site-packages/awscli/examples/route53/list-health-checks.rst
/lib/python2.7/site-packages/awscli/examples/route53/list-hosted-zones-by-name.rst
/lib/python2.7/site-packages/awscli/examples/route53/list-hosted-zones.rst
/lib/python2.7/site-packages/awscli/examples/route53/list-resource-record-sets.rst
/lib/python2.7/site-packages/awscli/examples/s3/_concepts.rst
/lib/python2.7/site-packages/awscli/examples/s3/cp.rst
/lib/python2.7/site-packages/awscli/examples/s3/ls.rst
/lib/python2.7/site-packages/awscli/examples/s3/mb.rst
/lib/python2.7/site-packages/awscli/examples/s3/mv.rst
/lib/python2.7/site-packages/awscli/examples/s3/rb.rst
/lib/python2.7/site-packages/awscli/examples/s3/rm.rst
/lib/python2.7/site-packages/awscli/examples/s3/sync.rst
/lib/python2.7/site-packages/awscli/examples/s3/website.rst
/lib/python2.7/site-packages/awscli/examples/s3api/abort-multipart-upload.rst
/lib/python2.7/site-packages/awscli/examples/s3api/complete-multipart-upload.rst
/lib/python2.7/site-packages/awscli/examples/s3api/copy-object.rst
/lib/python2.7/site-packages/awscli/examples/s3api/create-bucket.rst
/lib/python2.7/site-packages/awscli/examples/s3api/create-multipart-upload.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket-cors.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket-lifecycle.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket-policy.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket-replication.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket-tagging.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket-website.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-bucket.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-object.rst
/lib/python2.7/site-packages/awscli/examples/s3api/delete-objects.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-acl.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-cors.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-lifecycle-configuration.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-lifecycle.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-location.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-notification-configuration.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-notification.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-policy.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-replication.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-tagging.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-versioning.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-bucket-website.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-object-acl.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-object-torrent.rst
/lib/python2.7/site-packages/awscli/examples/s3api/get-object.rst
/lib/python2.7/site-packages/awscli/examples/s3api/head-bucket.rst
/lib/python2.7/site-packages/awscli/examples/s3api/head-object.rst
/lib/python2.7/site-packages/awscli/examples/s3api/list-buckets.rst
/lib/python2.7/site-packages/awscli/examples/s3api/list-multipart-uploads.rst
/lib/python2.7/site-packages/awscli/examples/s3api/list-object-versions.rst
/lib/python2.7/site-packages/awscli/examples/s3api/list-objects.rst
/lib/python2.7/site-packages/awscli/examples/s3api/list-parts.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-acl.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-cors.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-lifecycle-configuration.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-lifecycle.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-logging.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-notification-configuration.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-notification.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-policy.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-replication.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-tagging.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-versioning.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-bucket-website.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-object-acl.rst
/lib/python2.7/site-packages/awscli/examples/s3api/put-object.rst
/lib/python2.7/site-packages/awscli/examples/s3api/upload-part.rst
/lib/python2.7/site-packages/awscli/examples/ses/delete-identity.rst
/lib/python2.7/site-packages/awscli/examples/ses/get-identity-dkim-attributes.rst
/lib/python2.7/site-packages/awscli/examples/ses/get-identity-notification-attributes.rst
/lib/python2.7/site-packages/awscli/examples/ses/get-identity-verification-attributes.rst
/lib/python2.7/site-packages/awscli/examples/ses/get-send-quota.rst
/lib/python2.7/site-packages/awscli/examples/ses/get-send-statistics.rst
/lib/python2.7/site-packages/awscli/examples/ses/list-identities.rst
/lib/python2.7/site-packages/awscli/examples/ses/send-email.rst
/lib/python2.7/site-packages/awscli/examples/ses/send-raw-email.rst
/lib/python2.7/site-packages/awscli/examples/ses/set-identity-dkim-enabled.rst
/lib/python2.7/site-packages/awscli/examples/ses/set-identity-feedback-forwarding-enabled.rst
/lib/python2.7/site-packages/awscli/examples/ses/set-identity-notification-topic.rst
/lib/python2.7/site-packages/awscli/examples/ses/verify-domain-dkim.rst
/lib/python2.7/site-packages/awscli/examples/ses/verify-domain-identity.rst
/lib/python2.7/site-packages/awscli/examples/ses/verify-email-identity.rst
/lib/python2.7/site-packages/awscli/examples/sns/confirm-subscription.rst
/lib/python2.7/site-packages/awscli/examples/sns/create-topic.rst
/lib/python2.7/site-packages/awscli/examples/sns/delete-topic.rst
/lib/python2.7/site-packages/awscli/examples/sns/get-subscription-attributes.rst
/lib/python2.7/site-packages/awscli/examples/sns/get-topic-attributes.rst
/lib/python2.7/site-packages/awscli/examples/sns/list-subscriptions-by-topic.rst
/lib/python2.7/site-packages/awscli/examples/sns/list-subscriptions.rst
/lib/python2.7/site-packages/awscli/examples/sns/list-topics.rst
/lib/python2.7/site-packages/awscli/examples/sns/publish.rst
/lib/python2.7/site-packages/awscli/examples/sns/subscribe.rst
/lib/python2.7/site-packages/awscli/examples/sns/unsubscribe.rst
/lib/python2.7/site-packages/awscli/examples/sqs/add-permission.rst
/lib/python2.7/site-packages/awscli/examples/sqs/change-message-visibility-batch.rst
/lib/python2.7/site-packages/awscli/examples/sqs/change-message-visibility.rst
/lib/python2.7/site-packages/awscli/examples/sqs/create-queue.rst
/lib/python2.7/site-packages/awscli/examples/sqs/delete-message-batch.rst
/lib/python2.7/site-packages/awscli/examples/sqs/delete-message.rst
/lib/python2.7/site-packages/awscli/examples/sqs/delete-queue.rst
/lib/python2.7/site-packages/awscli/examples/sqs/get-queue-attributes.rst
/lib/python2.7/site-packages/awscli/examples/sqs/get-queue-url.rst
/lib/python2.7/site-packages/awscli/examples/sqs/list-dead-letter-source-queues.rst
/lib/python2.7/site-packages/awscli/examples/sqs/list-queues.rst
/lib/python2.7/site-packages/awscli/examples/sqs/purge-queue.rst
/lib/python2.7/site-packages/awscli/examples/sqs/receive-message.rst
/lib/python2.7/site-packages/awscli/examples/sqs/remove-permission.rst
/lib/python2.7/site-packages/awscli/examples/sqs/send-message-batch.rst
/lib/python2.7/site-packages/awscli/examples/sqs/send-message.rst
/lib/python2.7/site-packages/awscli/examples/sqs/set-queue-attributes.rst
/lib/python2.7/site-packages/awscli/examples/ssm/create-association-batch.rst
/lib/python2.7/site-packages/awscli/examples/ssm/create-association.rst
/lib/python2.7/site-packages/awscli/examples/ssm/create-document.rst
/lib/python2.7/site-packages/awscli/examples/ssm/delete-association.rst
/lib/python2.7/site-packages/awscli/examples/ssm/delete-document.rst
/lib/python2.7/site-packages/awscli/examples/ssm/describe-association.rst
/lib/python2.7/site-packages/awscli/examples/ssm/describe-document.rst
/lib/python2.7/site-packages/awscli/examples/ssm/get-document.rst
/lib/python2.7/site-packages/awscli/examples/ssm/list-associations.rst
/lib/python2.7/site-packages/awscli/examples/ssm/list-documents.rst
/lib/python2.7/site-packages/awscli/examples/ssm/update-association-status.rst
/lib/python2.7/site-packages/awscli/examples/storagegateway/describe-gateway-information.rst
/lib/python2.7/site-packages/awscli/examples/storagegateway/list-gateways.rst
/lib/python2.7/site-packages/awscli/examples/storagegateway/list-volumes.rst
/lib/python2.7/site-packages/awscli/examples/swf/count-closed-workflow-executions.rst
/lib/python2.7/site-packages/awscli/examples/swf/count-open-workflow-executions.rst
/lib/python2.7/site-packages/awscli/examples/swf/deprecate-domain.rst
/lib/python2.7/site-packages/awscli/examples/swf/describe-domain.rst
/lib/python2.7/site-packages/awscli/examples/swf/list-activity-types.rst
/lib/python2.7/site-packages/awscli/examples/swf/list-domains.rst
/lib/python2.7/site-packages/awscli/examples/swf/list-workflow-types.rst
/lib/python2.7/site-packages/awscli/examples/swf/register-domain.rst
/lib/python2.7/site-packages/awscli/examples/swf/register-workflow-type.rst
/lib/python2.7/site-packages/awscli/examples/workspaces/create-workspaces.rst
/lib/python2.7/site-packages/awscli/examples/workspaces/describe-workspace-bundles.rst
/lib/python2.7/site-packages/awscli/examples/workspaces/describe-workspace-directories.rst
/lib/python2.7/site-packages/awscli/examples/workspaces/describe-workspaces.rst
/lib/python2.7/site-packages/awscli/examples/workspaces/terminate-workspaces.rst
/lib/python2.7/site-packages/awscli/formatter.py
/lib/python2.7/site-packages/awscli/formatter.pyc
/lib/python2.7/site-packages/awscli/formatter.pyo
/lib/python2.7/site-packages/awscli/handlers.py
/lib/python2.7/site-packages/awscli/handlers.pyc
/lib/python2.7/site-packages/awscli/handlers.pyo
/lib/python2.7/site-packages/awscli/help.py
/lib/python2.7/site-packages/awscli/help.pyc
/lib/python2.7/site-packages/awscli/help.pyo
/lib/python2.7/site-packages/awscli/paramfile.py
/lib/python2.7/site-packages/awscli/paramfile.pyc
/lib/python2.7/site-packages/awscli/paramfile.pyo
/lib/python2.7/site-packages/awscli/plugin.py
/lib/python2.7/site-packages/awscli/plugin.pyc
/lib/python2.7/site-packages/awscli/plugin.pyo
/lib/python2.7/site-packages/awscli/schema.py
/lib/python2.7/site-packages/awscli/schema.pyc
/lib/python2.7/site-packages/awscli/schema.pyo
/lib/python2.7/site-packages/awscli/shorthand.py
/lib/python2.7/site-packages/awscli/shorthand.pyc
/lib/python2.7/site-packages/awscli/shorthand.pyo
/lib/python2.7/site-packages/awscli/table.py
/lib/python2.7/site-packages/awscli/table.pyc
/lib/python2.7/site-packages/awscli/table.pyo
/lib/python2.7/site-packages/awscli/testutils.py
/lib/python2.7/site-packages/awscli/testutils.pyc
/lib/python2.7/site-packages/awscli/testutils.pyo
/lib/python2.7/site-packages/awscli/text.py
/lib/python2.7/site-packages/awscli/text.pyc
/lib/python2.7/site-packages/awscli/text.pyo
/lib/python2.7/site-packages/awscli/topics/config-vars.rst
/lib/python2.7/site-packages/awscli/topics/return-codes.rst
/lib/python2.7/site-packages/awscli/topics/s3-config.rst
/lib/python2.7/site-packages/awscli/topics/topic-tags.json
/lib/python2.7/site-packages/awscli/topictags.py
/lib/python2.7/site-packages/awscli/topictags.pyc
/lib/python2.7/site-packages/awscli/topictags.pyo
/lib/python2.7/site-packages/awscli/utils.py
/lib/python2.7/site-packages/awscli/utils.pyc
/lib/python2.7/site-packages/awscli/utils.pyo

%changelog
* Mon Nov 16 2015 - robert (at) meinit.nl
- Initial release.
